language: node_js
node_js:
  - "node"

script:
  - npm run lint
  - npm run test:ci
  - npm run build

deploy:
  provider: npm
  email: "techleadcommunity@norauto.com"
  api_key: $NPM_TOKEN
  on:
    tags: true